services:
  - type: web
    name: fear-greed-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11